version: '3.1'

services:
  postgres:
    container_name: ouvimais_postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ouvimais
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432

volumes:
  postgres_data:
